### ISSUE TITLE
This software isn't functional anymore

### ISSUE THREAD

**Issue by hlorofos** [Chhekur/amazon-scraper#1]
Just in case someone will hit that repository accidentally - this doesn't work anymore,
hitting the following errors during crawl:

```
2019-10-03 09:46:52 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.amazon.in/Test-Exclusive-629/dp/B07HGLB1TJ/ref=sr_1_7?keywords=mobile&qid=1570085132&s=gateway&smid=A1EWEIV3F4B24B&sr=8-7> (referer: https://www.amazon.in/s?k=mobile)

IndexError: list index out of range
```

**Comment by Chhekur** [comment]
> Just in case someone will hit that repository accidentally - this doesn't work anymore,
> hitting the following errors during crawl:
> 
> ```
> 2019-10-03 09:46:52 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.amazon.in/Test-Exclusive-629/dp/B07HGLB1TJ/ref=sr_1_7?keywords=mobile&qid=1570085132&s=gateway&smid=A1EWEIV3F4B24B&sr=8-7> (referer: https://www.amazon.in/s?k=mobile)
> 
> IndexError: list index out of range
> ```

Please follow the instructions given in `README` file in order to make it work ; )

**Comment by hlorofos** [comment]
That makes no sense, since I already did that and run the spider

**Comment by Chhekur** [comment]
> That makes no sense, since I already did that and run the spider

Change the url with `https://www.amazon.in/s?k=clothes&ref=nb_sb_noss` in `amazon_scraper.py` at line 16

**Comment by Chhekur** [comment]
> That makes no sense, since I already did that and run the spider

Okay I'll try it by my own and then will ping you here once it is fixed ; )

**Comment by Chhekur** [comment]
> Just in case someone will hit that repository accidentally - this doesn't work anymore,
> hitting the following errors during crawl:
> 
> ```
> 2019-10-03 09:46:52 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.amazon.in/Test-Exclusive-629/dp/B07HGLB1TJ/ref=sr_1_7?keywords=mobile&qid=1570085132&s=gateway&smid=A1EWEIV3F4B24B&sr=8-7> (referer: https://www.amazon.in/s?k=mobile)
> 
> IndexError: list index out of range
> ```

Thanks for point out the mistake. I fixed that issue and updated the code accordingly and working fine now.
